import os
import asyncio
import hashlib
import json
import base64
import urllib.request
import re
import websockets
from typing import AsyncGenerator
from pathlib import Path
from openai import AsyncOpenAI
from abc import ABC, abstractmethod

import sys
sys.path.append(str(Path(__file__).resolve().parents[1]))

def normalize_phonetics(text: str) -> str:
    """Pre-processes text to fix common TTS pronunciation glitches."""
    # Remove language tags like [en], [hi], etc. generated by the LLM
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'\bDr\.', 'Doctor', text, flags=re.IGNORECASE)
    text = re.sub(r'\brs\.', 'rupees', text, flags=re.IGNORECASE)
    return text.strip()

class BaseTTSProvider(ABC):
    def __init__(self, output_dir: Path):
        self.output_dir = output_dir

    def get_cache_path(self, text: str, voice_key: str, wpm: int) -> Path:
        h = hashlib.md5(f"{text}|{voice_key}|{wpm}".encode("utf-8")).hexdigest()
        return self.output_dir / f"tts_{h}.mp3"

    @abstractmethod
    async def generate_speech(self, text: str, voice_key: str, target_wpm: int) -> AsyncGenerator[bytes, None]:
        pass

class OpenAITTSProvider(BaseTTSProvider):
    VOICE_MAP = {
        "en_neerja":  "nova", 
        "en_prabhat": "echo",
        "hi_swara":   "shimmer",
        "hi_madhur":  "onyx",
        "te_shruti":  "nova",
        "te_mohan":   "fable",
        "en": "nova",
        "hi": "shimmer",
        "te": "nova",
    }

    def __init__(self, output_dir: Path):
        super().__init__(output_dir)
        self.client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY", "dummy_key")) # Uses OPENAI_API_KEY
        print("Provider: OpenAI TTS initialized.")

    async def generate_speech(self, text: str, voice_key: str, target_wpm: int) -> AsyncGenerator[bytes, None]:
        voice_model = self.VOICE_MAP.get(voice_key, "nova")
        speed_scale = max(0.8, min(target_wpm / 150.0, 1.25))

        try:
            async with self.client.audio.speech.with_streaming_response.create(
                model="tts-1",
                voice=voice_model,
                input=text,
                response_format="pcm", # We need raw PCM for the frontend PCM player
                speed=speed_scale
            ) as response:
                # OpenAI API returns raw bytes in chunks. We yield them.
                async for chunk in response.iter_bytes():
                    yield chunk
        except Exception as e:
            print(f"  OpenAI TTS error: {e}")

class SarvamTTSProvider(BaseTTSProvider):
    # Sarvam maps to language codes. Voice gender is usually auto-selected or we can specify if supported.
    # For bulbul:v3, target_language_code is what matters most.
    LANG_MAP = {
        "en_neerja":  "en-IN", 
        "en_prabhat": "en-IN",
        "hi_swara":   "hi-IN",
        "hi_madhur":  "hi-IN",
        "te_shruti":  "te-IN",
        "te_mohan":   "te-IN",
        "en": "en-IN",
        "hi": "hi-IN",
        "te": "te-IN",
    }

    def __init__(self, output_dir: Path):
        super().__init__(output_dir)
        self.api_key = os.environ.get("SARVAM_API_KEY")
        print("Provider: Sarvam AI TTS initialized.")

    async def generate_speech(self, text: str, voice_key: str, target_wpm: int) -> AsyncGenerator[bytes, None]:
        lang_code = self.LANG_MAP.get(voice_key, "en-IN")
        
        try:
            # Connect to Sarvam Streaming WebSocket API
            uri = "wss://api.sarvam.ai/text-to-speech/ws?model=bulbul:v3"
            headers = {"api-subscription-key": self.api_key}
            
            async with websockets.connect(uri, additional_headers=headers) as ws:
                # 1. Send Config
                config_msg = {
                    "type": "config",
                    "data": {
                        "target_language_code": lang_code,
                        "speaker": "priya"
                    }
                }
                await ws.send(json.dumps(config_msg))
                
                # 2. Send Text
                text_msg = {
                    "type": "text",
                    "data": {
                        "text": text
                    }
                }
                await ws.send(json.dumps(text_msg))
                
                # 3. Send Flush to indicate end of generation for this sentence
                flush_msg = {"type": "flush", "data": {}}
                await ws.send(json.dumps(flush_msg))
                
                # 4. Read audio responses until stream ends
                while True:
                    try:
                        # Add a 2.0s timeout. If no chunks arrive, consider generation complete.
                        response = await asyncio.wait_for(ws.recv(), timeout=2.0)
                        res_json = json.loads(response)
                        
                        msg_type = res_json.get("type")
                        if msg_type == "audio" and "audio" in res_json.get("data", {}):
                            audio_b64 = res_json["data"]["audio"]
                            audio_bytes = base64.b64decode(audio_b64)
                            yield audio_bytes
                        elif msg_type in ["completion", "end"]:
                            break
                        elif msg_type == "error":
                            print(f"Sarvam WS Error: {res_json}")
                            break
                    except asyncio.TimeoutError:
                        break
                        
        except Exception as e:
            print(f"  Sarvam TTS WS error: {e}")

class TTSService:
    def __init__(self, output_dir: str = None):
        self.app_dir = Path(__file__).resolve().parent
        if output_dir is None:
            self.output_dir = self.app_dir / "static" / "audio"
        else:
            self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        provider_name = os.environ.get("TTS_PROVIDER", "openai").lower()
        if provider_name == "sarvam" and os.environ.get("SARVAM_API_KEY"):
            self.provider = SarvamTTSProvider(self.output_dir)
        else:
            self.provider = OpenAITTSProvider(self.output_dir)

    async def generate_speech(self, text: str, voice_key: str = "hi", target_wpm: int = 150) -> AsyncGenerator[bytes, None]:
        text = text.strip()
        if not any(c.isalnum() for c in text):
            return
            
        text = normalize_phonetics(text)
        async for chunk in self.provider.generate_speech(text, voice_key, target_wpm):
            yield chunk

    async def prewarm(self, voice_key: str = "hi"):
        pass

# CLI test
if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    async def test():
        tts = TTSService()
        url = await tts.generate_speech("नमस्ते, यह एक स्थानीय रूप से उत्पन्न आवाज़ है।", "hi", 150)
        print(f"Saved to {url}")

    asyncio.run(test())
